# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/php:7.2-node-browsers
    working_directory: ~/theme
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-php-dependencies-{{ checksum "composer.json" }}
          - v1-npm-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Install dependencies
          command: composer install -n --prefer-dist
      - save_cache:
          paths:
            - ./vendor
          key: v1-php-dependencies-{{ checksum "composer.json" }}
      - save_cache:
          paths:
            - node_modules
          key: v1-npm-dependencies-{{ checksum "package.json" }}
      - run:
          name: Build production version
          command: npm run build
      # Run tests!
      - run:
          name: Build production version
          command: ./vendor/bin/phpunit --bootstrap vendor/autoload.php tests/ExampleTest
